### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Mahtis** [uulkunie/Tsoha-Bootstrap#1]
Latasin projektin lauantaina 4.2.2017 klo 13.55

Vaikka dokumentointiin ei tarvinnut ottaa kantaa, niin haluan antaa siitä plussaa. Oikein hyvää ja nättiä dokumentointia; kaaviot ovat selkeitä, mutta relaatiokaaviossa hieman hämmensi se, että nuolet eivät osoita avaimiin, vaan luokkiin.

Koodia on ainakin omasta mielestäni tähän vaiheeseen nähden oikein hyvä määrä. Models-kansiosta olisi ehkä kannattanut poistaa category.php-tiedosto ennen committia, kun se näyttää olevan vain copy-paste todoitemistä, mutta siinä on joitain copy-paste rippeitä alkuperäisestä Game-luokasta. Hieman hämäsi aluksi koodin selausta.

Varsinainen TodoItem.php näyttää hyvältä. Kategorioiden liittämistä todoitemiin ei ole vielä toteutettu, mutta sen tarve on kuitenkin otettu huomioon. Olisiko findAll-metodissa hyvä laittaa tulokset järjestykseen? Esimerkiksi deadlinen perusteella, tai kun itemeillä kerran on urgency-attribuutti, niin kiireellisyyden mukaan? FindOne-metodiin liittyen, se palauttaa nullin, jos itemiä ei löydy. Tämä null voisi olla hyvä käsitellä TodoItemControllerissa, ja näyttä käyttäjälle esim. joku ilmoitus, jos etsittyä itemiä ei löydy (item($id)-metodissa).

TodoItemControllerin liittyen, itemien luontisivulla listataan kolme urgency-tasoa, mutta tietokannassa on vain kaksi, joten very urgent -itemin luontiyritys, johtaa virheilmoitukseen. Lisäksi luokassa on kaksi hyvin samannimistä luokkaa createItem ja newItem. NewItemia ei ole toteutettu ja epäilen sen olevan vain jäänne jostain aiemmasta suunnitelmasta, mutta se olisi siinä tapauksessa hyvä poistaa koodin luettavuuden parantamiseksi, sekä myös routes.php-tiedostosta. Jos kyse ei ole jäännösmetodista, niin suosittelen nimeämään sen eri tavalla, jotta ero createItemiin on selvä jo nimestä.

SQL:ään liittyen suosittelen UNIQUE-määritteiden lisäämistä ainakin accountin username ja urgency_levelin title/level -attribuuttien kohdalla (koska urgency levelit ovat kaikille käyttäjille yhteisiä). Muuten tietokanta näyttää hyvältä, enkä näe tietokantarakenteessa ongelmia.

Yleisesti projekti näyttää hyvältä ja koodi laadukkaalta, vaikka en kyllä php:tä juuri tunne. Myös ulkoasu näyttää hyvältä ja tarkoitukseen sopivalta. Tsemppiä projektiin, näyttää olevan hyvällä mallilla!

**Comment by uulkunie** [comment]
Kiitokset kattavasta palautteesta ja kehitysehdotuksista.
